/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EvidenceLocker__factory } from "./EvidenceLocker__factory";
export { EvidenceLocker__factory } from "./EvidenceLocker__factory";
