/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface EvidenceLockerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchorEvidence"
      | "evidenceByReport"
      | "getEvidenceCount"
      | "hashAnchored"
      | "verifyEvidence"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "anchorEvidence",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "evidenceByReport",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidenceCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "hashAnchored",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyEvidence",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "anchorEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evidenceByReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidenceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashAnchored",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyEvidence",
    data: BytesLike
  ): Result;
}

export interface EvidenceLocker extends BaseContract {
  connect(runner?: ContractRunner | null): EvidenceLocker;
  waitForDeployment(): Promise<this>;

  interface: EvidenceLockerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchorEvidence: TypedContractMethod<
    [reportId: string, cidHash: BytesLike],
    [void],
    "nonpayable"
  >;

  evidenceByReport: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [string, bigint, string] & {
        ipfsCidHash: string;
        timestamp: bigint;
        reportId: string;
      }
    ],
    "view"
  >;

  getEvidenceCount: TypedContractMethod<[reportId: string], [bigint], "view">;

  hashAnchored: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  verifyEvidence: TypedContractMethod<[cidHash: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchorEvidence"
  ): TypedContractMethod<
    [reportId: string, cidHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "evidenceByReport"
  ): TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [string, bigint, string] & {
        ipfsCidHash: string;
        timestamp: bigint;
        reportId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEvidenceCount"
  ): TypedContractMethod<[reportId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "hashAnchored"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyEvidence"
  ): TypedContractMethod<[cidHash: BytesLike], [boolean], "view">;

  filters: {};
}
