/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EvidenceLocker } from "./EvidenceLocker";
export * as factories from "./factories";
export { EvidenceLocker__factory } from "./factories/EvidenceLocker__factory";
